version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: my_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: my_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_USER}
    ports:
      - "5672:5672"   # Puerto AMQP para comunicación con NestJS
      - "15672:15672" # Interfaz web de RabbitMQ

volumes:
  mongo_data:
  mongo_config:
